author: En Zhou
year: 2022
license:
  header: This file is part of CLI application idev.
  text: |
    {{ .copyright }}

    This is my license. There are many like it, but this one is mine.
    My license is my best friend. It is my life. I must master it as I must
    master my life.
