version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/idev main.go

    run:
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go

    release:
        desc: Release the app locally
        cmds:
        - cp bin/idev $GOPATH/bin

    generate:
        desc: Generate Go code from protobuf
        cmds:
        - protoc --go_out=plugins=grpc:. --go_opt=paths=source_relative pkg/gopher/gopher.proto

    clean:
        desc: Remove all files in dist/
        cmds:
        - rm -rf dist/*

    test:
        desc: Execute Unit Tests
        cmds:
        - gotestsum --junitfile test-results/unit-tests.xml -- -short -race -cover -coverprofile test-results/cover.out ./...
