version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/idev main.go

    run:
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go

    release:
        desc: Release the app locally
        cmds:
        - cp bin/idev $GOPATH/bin

    clean:
        desc: Remove all files in dist/
        cmds:
        - rm -rf dist/*
